apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mongo.yaml
  - stockfish.yaml
  - model.yaml
  - playerservice.yaml
  - controller.yaml
  - lichess.yaml
  - frontend.yaml
