FROM sbtscala/scala-sbt:eclipse-temurin-alpine-25.0.1_8_1.12.9_3.3.7 AS builder
WORKDIR /app
COPY . .
RUN sbt sparkAnalytics/assembly

FROM eclipse-temurin:21-jre
WORKDIR /app
ENV SPARK_LOCAL_IP=127.0.0.1
COPY --from=builder /app/spark-analytics/target/scala-2.13/alu-chess-spark-analytics-assembly-*.jar app.jar
ENTRYPOINT ["java", "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED", "-jar", "app.jar"]
