FROM sbt:1.10.7-eclipse-temurin-21 AS builder
WORKDIR /app
COPY build.sbt .
COPY project/ project/
RUN sbt update
COPY . .
RUN sbt controller/assembly

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/controller/target/scala-3.6.4/alu-chess-controller-assembly-*.jar app.jar
EXPOSE 8081
ENV PORT=8081
ENTRYPOINT ["java", "-jar", "app.jar"]
