FROM sbtscala/scala-sbt:eclipse-temurin-alpine-25.0.1_8_1.12.9_3.3.7 AS builder
WORKDIR /app
COPY build.sbt .
COPY project/ project/
RUN sbt update
COPY . .
RUN sbt controller/assembly

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/controller/target/scala-3.6.4/alu-chess-controller-assembly-*.jar app.jar
EXPOSE 8081
ENV PORT=8081
ENTRYPOINT ["java", "-jar", "app.jar"]
