imagePullSecrets:
  - name: ghcr-secret

services:
  stockfish:
    image:
      tag: sha-0a6afb34d0ff3792b36e991d49f83b484c55f6d8
  model:
    image:
      tag: sha-0a6afb34d0ff3792b36e991d49f83b484c55f6d8
  playerservice:
    image:
      tag: sha-0a6afb34d0ff3792b36e991d49f83b484c55f6d8
  controller:
    image:
      tag: sha-0a6afb34d0ff3792b36e991d49f83b484c55f6d8
  lichess:
    image:
      tag: sha-0a6afb34d0ff3792b36e991d49f83b484c55f6d8
  frontend:
    image:
      repository: ghcr.io/luiszink/alu-chess-web
      tag: latest
